# Generated by Django 3.1.6 on 2021-02-05 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pigeonpost', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
