# Generated by Django 3.1.7 on 2021-02-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeonpost', '0003_comments_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
